<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.10.3" />
    <PackageReference Include="Jellyfin.Model" Version="10.10.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build.yaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\**\*" />
    <EmbeddedResource Include="Configuration\*.html" />
  </ItemGroup>

</Project>
